# Načtení modulů (ujistěte se, že mod_redirect je v seznamu)
server.modules += ( "mod_proxy", "mod_redirect" )

# --- OGN RF ---
url.redirect += ( "^/ogn-rf$" => "/ogn-rf/" )

$HTTP["url"] =~ "^/ogn-rf/" {
    proxy.header = (
        "map-urlpath" => ( "/ogn-rf/" => "/" ),
        "upgrade" => "enable"
    )
    proxy.forwarded = ( "for" => 1, "proto" => 1, "host" => 1 )
    proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => 8180 ) ) )
}

# --- OGN DEMODULATOR ---
url.redirect += ( "^/ogn-demodulator$" => "/ogn-demodulator/" )

$HTTP["url"] =~ "^/ogn-demodulator/" {
    proxy.header = (
        "map-urlpath" => ( "/ogn-demodulator/" => "/" ),
        "upgrade" => "enable"
    )
    proxy.forwarded = ( "for" => 1, "proto" => 1, "host" => 1 )
    proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => 8181 ) ) )
}
